fetch("https://api.starmakerstudios.com/web/login", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-IN,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,hi;q=0.6",
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "priority": "u=1, i",
    "sec-ch-ua": "\"Not:A-Brand\";v=\"99\", \"Google Chrome\";v=\"145\", \"Chromium\";v=\"145\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "x-locale": "en",
    "Referer": "https://www.starmakerstudios.com/"
  },
  "body": "x_auth_mode=email_login&x_auth_email=prashantrewar1311%40gmail.com&x_auth_password=StarPass%401311",
  "method": "POST"
});

var response = {
    "is_new_user": false,
    "has_stage_name": true,
    "has_profile_image": false,
    "id": "10696049130629862",
    "gender": 1,
    "tutorial_song_id": 0,
    "oauth_token": "boNEi7Gxc72wSGLfosuNcrjEQorx2TQB",
    "oauth_token_secret": "VO1NsneMYBE4od6ocdnVzdfzW2EwIsNX",
    "stage_name": "ReWaR",
    "signature": "xdxd",
    "portrait": "https://improxy.starmakerstudios.com/tools/im/200/production/users/10696049130629862/profile.jpg?ts=1771206616",
    "profile_image": "https://improxy.starmakerstudios.com/tools/im/200/production/users/10696049130629862/profile.jpg?ts=1771206616",
    "user": {
        "should_verify_age": false,
        "anonymous": false,
        "has_profile_image": true,
        "is_self": false,
        "is_verified": false,
        "is_vip": false,
        "is_hide_vip_tag": false,
        "is_show_decoration": false,
        "is_public": false,
        "is_noble_visiable": false,
        "is_noble": false,
        "is_new_user": false,
        "is_deleted": 0,
        "id": "10696049130629862",
        "age": 0,
        "gender": 1,
        "decoration_id": -1,
        "vip_level": 0,
        "user_level": 32,
        "ts": 1771363371,
        "token_count": 0,
        "recording_count": 0,
        "follower_count": 0,
        "sid": 100124245219,
        "name": "ReWaR",
        "stage_name": "ReWaR",
        "signature": "xdxd",
        "profile_image": "https://improxy.starmakerstudios.com/tools/im/200/production/users/10696049130629862/profile.jpg?ts=1771206616",
        "phone": "",
        "email": "",
        "hometown": "",
        "full_name": "",
        "birthday": "",
        "birthdate": "",
        "cover_image": "",
        "v_info": {},
        "honour_list": null,
        "honour_icon": "",
        "name_high": {
            "end_time": "0",
            "privilege_id": "0"
        },
        "family": {
            "slogan": "Δ(ɘxa_💗",
            "icon": "https://improxy.starmakerstudios.com/tools/im/0/production/statics/icon/family/a4fa3aebd941a99b.png",
            "background": "https://improxy.starmakerstudios.com/tools/im/0/production/statics/icon/family/new_level_ios_v2.png",
            "android_background": "https://improxy.starmakerstudios.com/tools/im/0/production/statics/icon/family/new_level_android_v2.9.png",
            "family_id": 3269104,
            "title": "ᴇɴᴅʟᴇss ᴍᴇᴍᴏʀɪᴇs 🫀",
            "user_role": {
                "role_id": 10,
                "role_name": "Admin"
            },
            "group_id": 5890405,
            "cover_url": "https://improxy.smintro.com/tools/im/0/files/6755399380107296/191a4b67680957173eab2128fa7fde7a.jpg",
            "region": "Area_IN"
        },
        "user_tags": null,
        "is_age_invisible": null,
        "earth_distance": "",
        "city": "",
        "vip_level_anim_icon": "",
        "vip_level_anim_icon_rtl": "",
        "tail_light": {
            "img_url": "https://improxy.starmakerstudios.com/tools/im/0/production/statics/tail_light/",
            "data": [
                {
                    "id": "513",
                    "weight": "0",
                    "mark": "other_basictitle1",
                    "icon": "ebffe56a-a0d8-4e06-a8af-e1b34d73716e.png",
                    "state": "0",
                    "type": "1",
                    "background": "",
                    "android_background": "",
                    "content": ""
                },
                {
                    "id": "514",
                    "weight": "0",
                    "mark": "other_basictitle2",
                    "icon": "0b410e9e-3d03-45f3-9460-31de60655464.png",
                    "state": "0",
                    "type": "1",
                    "background": "",
                    "android_background": "",
                    "content": ""
                },
                {
                    "id": "677",
                    "weight": "0",
                    "mark": "event_Forever Friends",
                    "icon": "afceb57c-1087-4541-9933-164819de5f8e.png",
                    "state": "0",
                    "type": "1",
                    "background": "",
                    "android_background": "",
                    "content": ""
                },
                {
                    "id": "515",
                    "weight": "0",
                    "mark": "other_basictitle3",
                    "icon": "7fb7ce49-f961-4a43-bd99-5032f02502c6.png",
                    "state": "0",
                    "type": "1",
                    "background": "",
                    "android_background": "",
                    "content": ""
                }
            ]
        },
        "card": {},
        "noble_privilege": {
            "is_open_noble": true,
            "is_open_noble_visiable": false,
            "noble_emperor_announce_open": false,
            "emperor_announce_open_entrance": false,
            "noble_id": "0",
            "noble_name": "",
            "end_time": "0",
            "icon_url": "https://improxy.starmakerstudios.com/tools/im/0,fpng/production/statics/icon/noble_v2.png",
            "noble_icon": "",
            "noble_url": "https://m.starmakerstudios.com/a-vue3/spa-noble-h5/?showBar=0\u0026showNavigation=false\u0026_sxiq_open_origin=Settings\u0026pg_rf_ca_vn=560"
        },
        "anchor_level_info": {
            "is_open_anchor_level": false,
            "acc_days": "0",
            "level": "0",
            "is_max_level": "0",
            "cur_exp": "0",
            "next_level_exp": "0",
            "today_exp": 0,
            "today_limit_exp": 3000,
            "updated_at": "0",
            "level_icon": "https://improxy.starmakerstudios.com/tools/im/0/production/statics/anchor/icon_anchor_level_privilege_0.png",
            "badge_icon": "",
            "privilege_icon": "https://improxy.starmakerstudios.com/tools/im/0/production/statics/anchor/icon_anchor_level_privilege_0.png",
            "next_privilege_icon": "https://improxy.starmakerstudios.com/tools/im/0//production/statics/anchor/icon_anchor_level_privilege_1.png"
        }
    }
}